/*
EXERCICIO 29
SELECIONE O USUÁRIO QUE TEM O SOBRENOME SMITH DA TABELA CUSTOMER
MUDE O NOME PARA MARY E O SOBRENOME PARA SMITH,
REMOVER A CAIXA ALTA DE TODAS AS LETRAS, DEIXAR SÓ NAS INICIAIS
CRIE ALIAS PARA AS DUAS COLUNAS QUE SERÃO: NOME E SOBRENOME
*/

SELECT REPLACE(first_name,"MARY","Mary")AS nome,
REPLACE(last_name, "SMITH","smith") AS sobrenome
FROM customer
WHERE last_name = "SMITH";
